FROM docker.ifeng.com/library/node:10.9.0 AS build

WORKDIR /ifeng-whale

RUN df -h && free -h && cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l && cat /proc/cpuinfo| grep "cpu cores"| uniq && cat /proc/cpuinfo| grep "processor"| wc -l

COPY *.json /ifeng-whale/
RUN npm --registry http://npm.ifengcloud.ifeng.com install

COPY . /ifeng-whale
RUN npm run build:test

# RUN cd ..
RUN NODE_ENV=production npm run uploadcdn magicapple V0rxeH2NNjHV31bNDJu4wQxyTh2wsdfKCcU6cQmb02Gg5hmvh1vnTM8XLAess9aGGRqTLK0Jxz7pjQfXipSo7Jo5C7a9iW3Y5EjHD2xFQlC1HF73yL7xBUIM7xahRoysfOkZjC0ZKVB7Ja9p8IaOw1nixOtTCGMVz1K3EwQnJJ7J8iFB4kTix3WmY5AdgOEl3GTawDstHrK09xAPdd6eK9aCgESqiIgTfEu5EtRuS65purCfj9jgAl4TbGMYutc0

FROM docker.ifeng.com/library/node:10.9.0-alpine

# ENV NODE_ENV ""
WORKDIR /ifeng-whale
EXPOSE 3000

COPY --from=build /ifeng-whale/*.json /ifeng-whale/
RUN npm --registry http://npm.ifengcloud.ifeng.com install  --production

COPY --from=build /ifeng-whale/*.js /ifeng-whale/
COPY --from=build /ifeng-whale/biz /ifeng-whale/biz
COPY --from=build /ifeng-whale/dist/*.html /ifeng-whale/dist/

CMD ["node","app.js"]