FROM docker.ifeng.com/library/node:8.9.3-alpine

WORKDIR /ifeng-whale

COPY package.json /ifeng-whale/
COPY package-lock.json /ifeng-whale/

RUN apk update && apk upgrade && apk add --no-cache bash git openssh

RUN npm --registry https://registry.npm.taobao.org install